### 新增/编辑组织
POST http://127.0.0.1:8888/org/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiIxNjE5NTA4MTE0ODI1NTU1OTcwIiwibWVtYmVyX2lkIjoiMTYxOTUwODQ4OTA2NjUyNDY3NCIsImNyZWF0ZV90ZW5hbnRfaWQiOiIxMzg1MDUzODQ1NTc5NjAzOTY5IiwidGVuYW50X25hbWUiOiLlpKnpl6jliIbooYwiLCJwYXNzIjoxNjE5NTA4MTE1MzA3OTAwOTMwLCJ1c2VyX25hbWUiOiIxNTAxMDEwMTAxMCIsInJvbGVzIjpbXSwiYWdlbmN5X2lkIjoiMTYxOTUwODExNDgyNTU1NTk3MCIsIm1lbWJlcl9uYW1lIjoi5p2O5pymIiwiY2xpZW50X2lkIjoicGMiLCJzeXN0ZW0iOjExLCJzY29wZSI6WyJzZXJ2ZXIiXSwicm9sZVR5cGVDb2RlcyI6bnVsbCwiaWQiOiIxNjE5NTA4NDg5MDA3ODA0NDE3IiwiZXhwIjoxNjc3NjM1NjQyLCJqdGkiOiIyMzEwMjMzZC1mZTAwLTRhZGYtOTgyZS0zNWY3NWZmNWIzZDQiLCJ1c2VybmFtZSI6IjE1MDEwMTAxMDEwIiwib3JnX2xvZ28iOm51bGx9.HMG5z3tcuGHKQuczqsSjhy347P8e7ld0iIObcUuZ72I

{
  "orgName":"测试",
  "superId":"-1",
  "orgType":"1"
}